package com.worldpay.test.oferrial.domain;

import java.util.UUID;

public class UniqueOfferId extends UriEncodableIdentifier implements OfferId {

    public static UniqueOfferId autoGenerated() {
        return new UniqueOfferId(UUID.randomUUID().toString());
    }

    public UniqueOfferId(OfferId id) {
        super(id.toIdString());
    }

    public UniqueOfferId(String id) {
        super(id);
    }

}
